//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSMMYM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contacto()
        {
            this.Respuesta = new HashSet<Respuesta>();
            this.Respuesta1 = new HashSet<Respuesta>();
        }
    
        public int id_contacto { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public string mensaje { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> id_usuario_contacto { get; set; }
        public Nullable<int> id_cotizacion { get; set; }
        public string estado { get; set; }
    
        public virtual Cotizacion Cotizacion { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta> Respuesta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Respuesta> Respuesta1 { get; set; }
    }
}
