//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSMMYM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CSMMYMEntities : DbContext
    {
        public CSMMYMEntities()
            : base("name=CSMMYMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contacto> Contacto { get; set; }
        public virtual DbSet<Cotizacion> Cotizacion { get; set; }
        public virtual DbSet<Detalle_Cotizacion> Detalle_Cotizacion { get; set; }
        public virtual DbSet<Pagina> Pagina { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Respuesta> Respuesta { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Servicio> Servicio { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual ObjectResult<Contacto_ID_Result> Contacto_ID(Nullable<int> id_contacto)
        {
            var id_contactoParameter = id_contacto.HasValue ?
                new ObjectParameter("id_contacto", id_contacto) :
                new ObjectParameter("id_contacto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Contacto_ID_Result>("Contacto_ID", id_contactoParameter);
        }
    
        public virtual ObjectResult<Contacto_Lista_Result> Contacto_Lista()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Contacto_Lista_Result>("Contacto_Lista");
        }
    
        public virtual int Cotizacion_Insert(Nullable<int> id_usuario_creador, string nombre, string correo, string detalle)
        {
            var id_usuario_creadorParameter = id_usuario_creador.HasValue ?
                new ObjectParameter("id_usuario_creador", id_usuario_creador) :
                new ObjectParameter("id_usuario_creador", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var detalleParameter = detalle != null ?
                new ObjectParameter("detalle", detalle) :
                new ObjectParameter("detalle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Cotizacion_Insert", id_usuario_creadorParameter, nombreParameter, correoParameter, detalleParameter);
        }
    
        public virtual int Delete_Pagina(Nullable<int> id_pagina, Nullable<int> id_usuario_editor)
        {
            var id_paginaParameter = id_pagina.HasValue ?
                new ObjectParameter("id_pagina", id_pagina) :
                new ObjectParameter("id_pagina", typeof(int));
    
            var id_usuario_editorParameter = id_usuario_editor.HasValue ?
                new ObjectParameter("id_usuario_editor", id_usuario_editor) :
                new ObjectParameter("id_usuario_editor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Pagina", id_paginaParameter, id_usuario_editorParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> Insert_PaginaContenido(string titulo, string contenido, string tipo, string seccion, string estado, Nullable<int> id_usuario_editor)
        {
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var contenidoParameter = contenido != null ?
                new ObjectParameter("contenido", contenido) :
                new ObjectParameter("contenido", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var seccionParameter = seccion != null ?
                new ObjectParameter("seccion", seccion) :
                new ObjectParameter("seccion", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var id_usuario_editorParameter = id_usuario_editor.HasValue ?
                new ObjectParameter("id_usuario_editor", id_usuario_editor) :
                new ObjectParameter("id_usuario_editor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("Insert_PaginaContenido", tituloParameter, contenidoParameter, tipoParameter, seccionParameter, estadoParameter, id_usuario_editorParameter);
        }
    
        public virtual int Insert_Producto(string nombre, string tipo, Nullable<decimal> precio, string descripcion, string estado, string imagen)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Producto", nombreParameter, tipoParameter, precioParameter, descripcionParameter, estadoParameter, imagenParameter);
        }
    
        public virtual int Insert_Servicio(string nombre, string tipo, Nullable<decimal> precio_base, string estado, string imagen)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var precio_baseParameter = precio_base.HasValue ?
                new ObjectParameter("precio_base", precio_base) :
                new ObjectParameter("precio_base", typeof(decimal));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Servicio", nombreParameter, tipoParameter, precio_baseParameter, estadoParameter, imagenParameter);
        }
    
        public virtual ObjectResult<PaginaContenido_ListByTipo_Result> PaginaContenido_ListByTipo(string tipo)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PaginaContenido_ListByTipo_Result>("PaginaContenido_ListByTipo", tipoParameter);
        }
    
        public virtual int PaginaContenido_Update(Nullable<int> id_pagina, string titulo, string contenido, string tipo, string seccion, string estado, Nullable<int> id_usuario_editor)
        {
            var id_paginaParameter = id_pagina.HasValue ?
                new ObjectParameter("id_pagina", id_pagina) :
                new ObjectParameter("id_pagina", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("titulo", titulo) :
                new ObjectParameter("titulo", typeof(string));
    
            var contenidoParameter = contenido != null ?
                new ObjectParameter("contenido", contenido) :
                new ObjectParameter("contenido", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var seccionParameter = seccion != null ?
                new ObjectParameter("seccion", seccion) :
                new ObjectParameter("seccion", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var id_usuario_editorParameter = id_usuario_editor.HasValue ?
                new ObjectParameter("id_usuario_editor", id_usuario_editor) :
                new ObjectParameter("id_usuario_editor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PaginaContenido_Update", id_paginaParameter, tituloParameter, contenidoParameter, tipoParameter, seccionParameter, estadoParameter, id_usuario_editorParameter);
        }
    
        public virtual int ProductoUpdate(Nullable<int> id_producto, string nombre, string tipo, Nullable<decimal> precio, string descripcion, string imagen)
        {
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("id_producto", id_producto) :
                new ObjectParameter("id_producto", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(decimal));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductoUpdate", id_productoParameter, nombreParameter, tipoParameter, precioParameter, descripcionParameter, imagenParameter);
        }
    
        public virtual ObjectResult<Reporte_Productos_Result> Reporte_Productos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Reporte_Productos_Result>("Reporte_Productos");
        }
    
        public virtual ObjectResult<Reporte_Servicio_Result> Reporte_Servicio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Reporte_Servicio_Result>("Reporte_Servicio");
        }
    
        public virtual int Respuesta_Insert(Nullable<int> id_contacto, string mensaje)
        {
            var id_contactoParameter = id_contacto.HasValue ?
                new ObjectParameter("id_contacto", id_contacto) :
                new ObjectParameter("id_contacto", typeof(int));
    
            var mensajeParameter = mensaje != null ?
                new ObjectParameter("mensaje", mensaje) :
                new ObjectParameter("mensaje", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Respuesta_Insert", id_contactoParameter, mensajeParameter);
        }
    
        public virtual ObjectResult<Respuesta_ListarPorCotizacion_Result> Respuesta_ListarPorCotizacion(Nullable<int> id_cotizacion)
        {
            var id_cotizacionParameter = id_cotizacion.HasValue ?
                new ObjectParameter("id_cotizacion", id_cotizacion) :
                new ObjectParameter("id_cotizacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Respuesta_ListarPorCotizacion_Result>("Respuesta_ListarPorCotizacion", id_cotizacionParameter);
        }
    
        public virtual ObjectResult<RetornaPaginaContenido_ID_Result> RetornaPaginaContenido_ID(Nullable<int> id_pagina)
        {
            var id_paginaParameter = id_pagina.HasValue ?
                new ObjectParameter("id_pagina", id_pagina) :
                new ObjectParameter("id_pagina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaPaginaContenido_ID_Result>("RetornaPaginaContenido_ID", id_paginaParameter);
        }
    
        public virtual ObjectResult<RetornaProducto_ID_Result> RetornaProducto_ID(Nullable<int> id_producto)
        {
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("id_producto", id_producto) :
                new ObjectParameter("id_producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaProducto_ID_Result>("RetornaProducto_ID", id_productoParameter);
        }
    
        public virtual ObjectResult<RetornaServicio_ID_Result> RetornaServicio_ID(Nullable<int> id_servicio)
        {
            var id_servicioParameter = id_servicio.HasValue ?
                new ObjectParameter("id_servicio", id_servicio) :
                new ObjectParameter("id_servicio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetornaServicio_ID_Result>("RetornaServicio_ID", id_servicioParameter);
        }
    
        public virtual ObjectResult<Rol_Listar_Result> Rol_Listar()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rol_Listar_Result>("Rol_Listar");
        }
    
        public virtual ObjectResult<Rol_Select_Result> Rol_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rol_Select_Result>("Rol_Select");
        }
    
        public virtual ObjectResult<Select_Producto_Result> Select_Producto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Producto_Result>("Select_Producto");
        }
    
        public virtual ObjectResult<Select_Servicio_Result> Select_Servicio()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Servicio_Result>("Select_Servicio");
        }
    
        public virtual ObjectResult<SelectPaginaContenido_Result> SelectPaginaContenido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectPaginaContenido_Result>("SelectPaginaContenido");
        }
    
        public virtual int ServicioUpdate(Nullable<int> id_servicio, string nombre, string tipo, Nullable<decimal> precio_base, string imagen)
        {
            var id_servicioParameter = id_servicio.HasValue ?
                new ObjectParameter("id_servicio", id_servicio) :
                new ObjectParameter("id_servicio", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var precio_baseParameter = precio_base.HasValue ?
                new ObjectParameter("precio_base", precio_base) :
                new ObjectParameter("precio_base", typeof(decimal));
    
            var imagenParameter = imagen != null ?
                new ObjectParameter("imagen", imagen) :
                new ObjectParameter("imagen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ServicioUpdate", id_servicioParameter, nombreParameter, tipoParameter, precio_baseParameter, imagenParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_DeshabilitarProducto(Nullable<int> id_producto)
        {
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("id_producto", id_producto) :
                new ObjectParameter("id_producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeshabilitarProducto", id_productoParameter);
        }
    
        public virtual int sp_DeshabilitarSeccion(Nullable<int> id_pagina)
        {
            var id_paginaParameter = id_pagina.HasValue ?
                new ObjectParameter("id_pagina", id_pagina) :
                new ObjectParameter("id_pagina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeshabilitarSeccion", id_paginaParameter);
        }
    
        public virtual int sp_DeshabilitarServicio(Nullable<int> id_servicio)
        {
            var id_servicioParameter = id_servicio.HasValue ?
                new ObjectParameter("id_servicio", id_servicio) :
                new ObjectParameter("id_servicio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeshabilitarServicio", id_servicioParameter);
        }
    
        public virtual int sp_DeshabilitarUsuario(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DeshabilitarUsuario", id_usuarioParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_HabilitarProducto(Nullable<int> id_producto)
        {
            var id_productoParameter = id_producto.HasValue ?
                new ObjectParameter("id_producto", id_producto) :
                new ObjectParameter("id_producto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HabilitarProducto", id_productoParameter);
        }
    
        public virtual int sp_HabilitarSeccion(Nullable<int> id_pagina)
        {
            var id_paginaParameter = id_pagina.HasValue ?
                new ObjectParameter("id_pagina", id_pagina) :
                new ObjectParameter("id_pagina", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HabilitarSeccion", id_paginaParameter);
        }
    
        public virtual int sp_HabilitarServicio(Nullable<int> id_servicio)
        {
            var id_servicioParameter = id_servicio.HasValue ?
                new ObjectParameter("id_servicio", id_servicio) :
                new ObjectParameter("id_servicio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HabilitarServicio", id_servicioParameter);
        }
    
        public virtual int sp_HabilitarUsuario(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HabilitarUsuario", id_usuarioParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_PaginaContenido_Get_Result> sp_PaginaContenido_Get(string tipo, string seccion)
        {
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            var seccionParameter = seccion != null ?
                new ObjectParameter("seccion", seccion) :
                new ObjectParameter("seccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_PaginaContenido_Get_Result>("sp_PaginaContenido_Get", tipoParameter, seccionParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int Usuario_CambiarContrasena(Nullable<int> id_usuario, string contrasena)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usuario_CambiarContrasena", id_usuarioParameter, contrasenaParameter);
        }
    
        public virtual int Usuario_Insert(string usuario, string nombre, string correo, string contrasena, string estado, Nullable<int> id_rol)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var contrasenaParameter = contrasena != null ?
                new ObjectParameter("contrasena", contrasena) :
                new ObjectParameter("contrasena", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var id_rolParameter = id_rol.HasValue ?
                new ObjectParameter("id_rol", id_rol) :
                new ObjectParameter("id_rol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usuario_Insert", usuarioParameter, nombreParameter, correoParameter, contrasenaParameter, estadoParameter, id_rolParameter);
        }
    
        public virtual ObjectResult<Usuario_Select_Result> Usuario_Select()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario_Select_Result>("Usuario_Select");
        }
    
        public virtual ObjectResult<Usuario_Select_Id_Result> Usuario_Select_Id(Nullable<int> id_usuario)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Usuario_Select_Id_Result>("Usuario_Select_Id", id_usuarioParameter);
        }
    
        public virtual int Usuario_Update(Nullable<int> id_usuario, string nombre, string usuario, Nullable<int> id_rol, string estado)
        {
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            var id_rolParameter = id_rol.HasValue ?
                new ObjectParameter("id_rol", id_rol) :
                new ObjectParameter("id_rol", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Usuario_Update", id_usuarioParameter, nombreParameter, usuarioParameter, id_rolParameter, estadoParameter);
        }
    }
}
