//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSMMYM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Cotizacion
    {
        public int id_detalle { get; set; }
        public int id_cotizacion { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public int cantidad { get; set; }
        public Nullable<int> duracion { get; set; }
        public decimal precio_unitario { get; set; }
    
        public virtual Cotizacion Cotizacion { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
