//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSMMYM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagina
    {
        public int id_pagina { get; set; }
        public string titulo { get; set; }
        public string contenido { get; set; }
        public string tipo { get; set; }
        public Nullable<int> id_usuario_editor { get; set; }
        public System.DateTime fecha_edicion { get; set; }
        public string estado { get; set; }
        public string seccion { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
