//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSMMYM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respuesta
    {
        public int id_respuesta { get; set; }
        public Nullable<int> id_cotizacion { get; set; }
        public int id_usuario_autor { get; set; }
        public string mensaje { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<int> IdContacto { get; set; }
    
        public virtual Contacto Contacto { get; set; }
        public virtual Contacto Contacto1 { get; set; }
        public virtual Cotizacion Cotizacion { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
